return
{
    cpumatch = '%d*%-BG%-%d*',
    items =
    {
        { level = 1,   batch = 1, selector = { name = 'gregtech:gt.metaitem.01', damage = 32764 } }, -- BrainTech
        { level = 1024, batch = 64, selector = { label = 'Stone' } },
        { level = 1,   batch = 1, selector = { label = 'Sky Stone Dust' } },
        { level = 32,  batch = 32, selector = { label = 'Phthalic Acid Cell' } },
        { level = 32,  batch = 32, selector = { label = 'Hydrofluoric Acid Cell' } },
        { level = 32,  batch = 32, selector = { label = 'Hydrochloric Acid Cell' } },
        { level = 32,  batch = 32, selector = { label = 'Phosphoric Acid Cell' } },
        { level = 4,   batch = 4, selector = { label = 'XP Bucket' } },
        { level = 256, batch = 1, selector = { label = 'Sunnarium Dust' } },
        { level = 1,   batch = 1, selector = { label = 'Palladium Salt Dust' } },
        { level = 256, batch = 1, selector = { label = 'Osmium Dust' } },
        { level = 1024, batch = 4, selector = { label = 'Palladium Dust' } },
        { level = 256, batch = 1, selector = { label = '60k NaK Coolant Cell' } },
        { level = 512, batch = 16, selector = { label = 'Graphite Dust' } },
        { level = 128, batch = 32, selector = { label = 'Phosphorus doped Wafer' } },
        { level = 64,  batch = 16, selector = { label = 'Wafer' } },
        { level = 16,  batch = 1, selector = { label = 'Output Bus (HV)' } },
        { level = 16,  batch = 1, selector = { label = 'Input Bus (HV)' } },
        { level = 10000, batch = 1, selector = { label = 'Rutile Dust' } },
        { level = 1024, batch = 1, selector = { label = 'Platinum Dust' } },
        { level = 1024, batch = 1, selector = { label = 'Iridium Dust' } },
        { level = 256, batch = 1, selector = { label = 'Quad Fuel Rod (Uranium)' } },
        { level = 512, batch = 8, selector = { label = 'Silicon Solar Grade (Poly SI) Dust' } },
        { level = 24,  batch = 1, selector = { label = 'Lapotron Crystal' } },
        { level = 8,   batch = 1, selector = { label = 'EV Energy Hatch' } },
        { level = 1024, batch = 1, selector = { label = 'Electrum Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Blue Alloy Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Cupronickel Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Brass Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Bronze Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Tumbaga Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Invar Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Red Alloy Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Glowstone' } },
        { level = 256, batch = 1, selector = { label = 'Eye of Ender' } },
        { level = 256, batch = 1, selector = { label = '1x Superconductor EV Wire' } },
        { level = 256, batch = 1, selector = { label = '1x Superconductor HV Wire' } },
        { level = 16,  batch = 1, selector = { label = 'LV Machine Hull' } },
        { level = 8,   batch = 1, selector = { label = 'Extreme Transformer' } },
        -- { level = 8,   batch = 1, selector = { label = 'Insane Transformer' } },
        { level = 8,   batch = 1, selector = { label = 'EV Hi-Amp Transformer' } },
        { level = 8,   batch = 1, selector = { label = 'Turbo Gas Turbine' } },
        { level = 24,  batch = 1, selector = { label = 'Energy Crystal' } },
        { level = 10,  batch = 1, selector = { label = 'ME Multi-Fluid Storage Housing' } },
        { level = 256, batch = 1, selector = { label = 'Quicksilver' } },


        { level = 256, batch = 1, selector = { label = 'Blue Steel Ingot' } },
        { level = 1024, batch = 1, selector = { label = 'Annealed Copper Ingot' } },
        { level = 1024, batch = 1, selector = { label = 'SMD Capacitor' } },
        { level = 1024, batch = 1, selector = { label = 'SMD Diode' } },
        { level = 1024, batch = 1, selector = { label = 'SMD Inductor' } },
        { level = 1024, batch = 1, selector = { label = 'SMD Resistor' } },
        { level = 1024, batch = 1, selector = { label = 'SMD Transistor' } },

        -- Thaumcraft
        { level = 128, batch = 1, selector = { label = 'Air Shard' } },
        { level = 128, batch = 1, selector = { label = 'Balanced Shard' } },
        { level = 128, batch = 1, selector = { label = 'Earth Shard' } },
        { level = 128, batch = 1, selector = { label = 'Entropy Shard' } },
        { level = 128, batch = 1, selector = { label = 'Fire Shard' } },
        { level = 128, batch = 1, selector = { label = 'Order Shard' } },
        { level = 128, batch = 1, selector = { label = 'Water Shard' } },
        { level = 256, batch = 1, selector = { label = 'Tantalum Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Thaumium Ingot' } },

        -- EBF
        { level = 2048, batch = 1, selector = { label = 'Steel Ingot' } },
        { level = 2048, batch = 1, selector = { label = 'Aluminium Ingot' } },
        { level = 2048, batch = 1, selector = { label = 'Stainless Steel Ingot' } },
        { level = 2048, batch = 1, selector = { label = 'Titanium Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Tungsten Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Tungstensteel Ingot' } },
        { level = 256, batch = 1, selector = { label = 'TVP-Alloy Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Pulsating Iron Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Vibrant Alloy Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Void Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Black Steel Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Chrome Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Conductive Iron Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Crystalline Alloy Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Electrical Steel Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Energetic Alloy Ingot' } },
        { level = 256, batch = 1, selector = { label = 'HSS-G Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Kanthal Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Nichrome Ingot' } },
        { level = 16,  batch = 1, selector = { label = 'Rose Gold Ingot' } },
        { level = 16,  batch = 1, selector = { label = 'Shadow Metal Ingot' } },
        { level = 16,  batch = 1, selector = { label = 'End Steel Ingot' } },
        { level = 16,  batch = 1, selector = { label = 'Niobium-Titanium Ingot' } },
        { level = 16,  batch = 1, selector = { label = 'Enderium Ingot' } },
        { level = 16,  batch = 1, selector = { label = 'Neodymium Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Redstone Alloy Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Silicon Solar Grade (Poly SI) Ingot' } },
    }
}
