return
{
    cpumatch = '%d*%-BG%-%d*',
    items =
    {
        { level = 1, batch = 1, selector = { label = 'BrainTech Aerospace Advanced Reinforced Duct Tape FAL-84' } },
        { level = 1024, batch = 64, selector = { label = 'Stone' } },
        { level = 1, batch = 1, selector = { label = 'Sky Stone Dust' } },
        { level = 32, batch = 32, selector = { label = 'Phthalic Acid Cell' } },
        { level = 32, batch = 32, selector = { label = 'Hydrofluoric Acid Cell' } },
        { level = 32, batch = 32, selector = { label = 'Hydrochloric Acid Cell' } },
        { level = 32, batch = 32, selector = { label = 'Phosphoric Acid Cell' } },
        { level = 4, batch = 4, selector = { label = 'XP Bucket' } },
        { level = 1024, batch = 1, selector = { label = 'Sunnarium Dust' } },
        { level = 1, batch = 1, selector = { label = 'Palladium Salt Dust' } },
        { level = 256, batch = 1, selector = { label = 'Osmium Dust' } },
        { level = 1024, batch = 4, selector = { label = 'Palladium Dust' } },
        { level = 256, batch = 1, selector = { label = '60k NaK Coolant Cell' } },
        { level = 512, batch = 16, selector = { label = 'Graphite Dust' } },
        { level = 128, batch = 32, selector = { label = 'Phosphorus doped Wafer' } },
        { level = 64, batch = 16, selector = { label = 'Wafer' } },
        { lock = 'complex',  level = 16, batch = 1, selector = { label = 'Output Bus (HV)' } },
        { lock = 'complex',  level = 16, batch = 1, selector = { label = 'Input Bus (HV)' } },
        { level = 10000, batch = 1, selector = { label = 'Rutile Dust' } },
        { level = 1024, batch = 1, selector = { label = 'Platinum Dust' } },
        { level = 1024, batch = 1, selector = { label = 'Iridium Dust' } },
        { level = 256, batch = 1, selector = { label = 'Quad Fuel Rod (Uranium)' } },
        { level = 512, batch = 8, selector = { label = 'Silicon Solar Grade (Poly SI) Dust' } },
        { level = 24, batch = 1, selector = { label = 'Lapotron Crystal' } },
        { level = 8, batch = 1, selector = { label = 'EV Energy Hatch' } },
        { level = 256, batch = 1, selector = { label = 'Cupronickel Ingot' } },
        { level = 256, batch = 1, selector = { label = 'Glowstone' } },
        { level = 256, batch = 1, selector = { label = 'Eye of Ender' } },
        { level = 256, batch = 1, selector = { label = '1x Superconductor EV Wire' } },
        { level = 256, batch = 1, selector = { label = '1x Superconductor HV Wire' } },
        { level = 16, batch = 1, selector = { label = 'LV Machine Hull' } },
        { level = 8, batch = 1, selector = { label = 'Extreme Transformer' } },
        -- { level = 8, batch = 1, selector = { label = 'Insane Transformer' } },
        { level = 8, batch = 1, selector = { label = 'EV Hi-Amp Transformer' } },
        { level = 8, batch = 1, selector = { label = 'Turbo Gas Turbine' } },
        { level = 24, batch = 1, selector = { label = 'Energy Crystal' } },
        { level = 10, batch = 1, selector = { label = 'ME Multi-Fluid Storage Housing' } },
        { level = 256, batch = 1, selector = { label = 'Quicksilver' } },
        { level = 1024, batch = 1, selector = { label = 'Annealed Copper Ingot' } },
        { level = 1024, batch = 1, selector = { label = 'SMD Capacitor' } },
        { level = 1024, batch = 1, selector = { label = 'SMD Diode' } },
        { level = 1024, batch = 1, selector = { label = 'SMD Inductor' } },
        { level = 1024, batch = 1, selector = { label = 'SMD Resistor' } },
        { level = 1024, batch = 1, selector = { label = 'SMD Transistor' } },
        { level = 1024,             batch = 1,    selector = { label = 'Annealed Copper Ingot' } },
        -- Needs better vanadium source
        -- { level = 256, batch = 1, selector = { label = 'Advanced SMD Capacitor' } },
        -- { level = 256, batch = 1, selector = { label = 'Advanced SMD Diode' } },
        -- { level = 256, batch = 1, selector = { label = 'Advanced SMD Inductor' } },
        -- { level = 256, batch = 1, selector = { label = 'Advanced SMD Resistor' } },
        -- { level = 256, batch = 1, selector = { label = 'Advanced SMD Transistor' } },

        { lock = 'complex', level = 16, batch = 1, selector = { label = 'Output Bus (ME)' } },
        { lock = 'complex', level = 16, batch = 1, selector = { label = 'Output Hatch (ME)' } },
        { lock = 'complex', level = 16, batch = 1, selector = { label = 'Input Hatch (LV)' } },
        { lock = 'complex', level = 16, batch = 1, selector = { label = 'Output Hatch (LV)' } },
        { lock = 'complex', level = 16, batch = 1, selector = { label = 'Muffler Hatch (EV)' } },
        { lock = 'complex', level = 4, batch = 1, selector = { label = 'EV Dynamo Hatch' } },
        { lock = 'complex', level = 4, batch = 1, selector = { label = 'EV 4A Dynamo Hatch' } },
        { lock = 'complex', level = 16, batch = 1, selector = { label = 'Maintenance Hatch' } },
        { lock = 'complex', level = 16, batch = 1, selector = { label = 'Needs Maintenance Cover' } },
        { lock = 'complex', level = 16, batch = 1, selector = { label = 'Energy Cover' } },
        { lock = 'complex', level = 16, batch = 1, selector = { label = 'Machine Controller Cover' } },
        { lock = 'complex', level = 4, batch = 1, selector = { label = 'Pattern Capacity Card' } },
        { lock = 'complex', level = 4, batch = 1, selector = { label = '64k ME Storage Component' } },
        { lock = 'complex', level = 4, batch = 1, selector = { label = '64k ME Fluid Storage Component' } },
        { lock = 'complex', level = 4, batch = 1, selector = { label = '64k ME Fluid Storage Cell' } },
        { lock = 'complex', level = 4, batch = 1, selector = { label = '64k ME Multi-Fluid Storage Cell' } },
        { lock = 'complex', level = 4, batch = 1, selector = { label = '64k ME Storage Cell' } },
        
        -- OpenComputers stuff
        { lock = 'complex_os', level = 100, batch = 10, selector = { label = 'Cable' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Accelerated Processing Unit (APU) (Tier 1)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Accelerated Processing Unit (APU) (Tier 2)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Central Processing Unit (CPU) (Tier 1)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Central Processing Unit (CPU) (Tier 2)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Central Processing Unit (CPU) (Tier 3)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Graphics Card (Tier 3)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Computer Case (Tier 2)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Computer Case (Tier 3)' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'Charger' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Data Card (Tier 1)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Data Card (Tier 3)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Geolyzer' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'Hard Disk Drive (Tier 1) (1MB)' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'Hard Disk Drive (Tier 2) (2MB)' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'Hard Disk Drive (Tier 3) (4MB)' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'Adapter' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'EEPROM (Lua Bios)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Internet Card' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Inventory Controller Upgrade' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Inventory Upgrade' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'Keyboard' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Linked Card' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'Memory (Tier 1)' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'Memory (Tier 1.5)' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'Memory (Tier 2)' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'Memory (Tier 3)' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'Memory (Tier 3.5)' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'Network Card' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'Power Converter' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Redstone Card (Tier 1)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'RITEG Upgrade' } },
        { lock = 'complex_os', level = 6, batch = 1, selector = { label = 'Screen (Tier 1)' } },
        { lock = 'complex_os', level = 6, batch = 1, selector = { label = 'Screen (Tier 2)' } },
        { lock = 'complex_os', level = 6, batch = 1, selector = { label = 'Screen (Tier 3)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Configurator Upgrade' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Disk Drive' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Tablet Case (Tier 2)' } },
        { lock = 'complex_os', level = 4, batch = 1, selector = { label = 'Wireless Network Card (Tier 2)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Upgrade Container (Tier 3)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Card Container (Tier 3)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Card Container (Tier 2)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Database Upgrade (Tier 1)' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Generator Upgrade' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'TPS Card' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Transposer' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Solar Generator Upgrade' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Relay' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Rack' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Raid' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'MFU' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Navigation Upgrade' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Crafting Upgrade' } },
        { lock = 'complex_os', level = 2, batch = 1, selector = { label = 'Capacitor' } },
        { lock = 'complex_os', level = 8, batch = 1, selector = { label = 'Robot.name' } },

        -- Alloy Smelter
        { lock = 'alloysmelter', level = 256, batch = 1, selector = { label = 'Blue Steel Ingot' } },
        { lock = 'alloysmelter', level = 1024, batch = 1, selector = { label = 'Electrum Ingot' } },
        { lock = 'alloysmelter', level = 256, batch = 1, selector = { label = 'Blue Alloy Ingot' } },
        { lock = 'alloysmelter', level = 256, batch = 1, selector = { label = 'Brass Ingot' } },
        { lock = 'alloysmelter', level = 256, batch = 1, selector = { label = 'Bronze Ingot' } },
        { lock = 'alloysmelter', level = 256, batch = 1, selector = { label = 'Tumbaga Ingot' } },
        { lock = 'alloysmelter', level = 256, batch = 1, selector = { label = 'Invar Ingot' } },
        { lock = 'alloysmelter', level = 256, batch = 1, selector = { label = 'Red Alloy Ingot' } },

        -- Thaumcraft
        { lock = 'thaumcraft', level = 128, batch = 1, selector = { label = 'Air Shard' } },
        { lock = 'thaumcraft', level = 128, batch = 1, selector = { label = 'Balanced Shard' } },
        { lock = 'thaumcraft', level = 128, batch = 1, selector = { label = 'Earth Shard' } },
        { lock = 'thaumcraft', level = 128, batch = 1, selector = { label = 'Entropy Shard' } },
        { lock = 'thaumcraft', level = 128, batch = 1, selector = { label = 'Fire Shard' } },
        { lock = 'thaumcraft', level = 128, batch = 1, selector = { label = 'Order Shard' } },
        { lock = 'thaumcraft', level = 128, batch = 1, selector = { label = 'Water Shard' } },
        { lock = 'thaumcraft', level = 256, batch = 1, selector = { label = 'Tantalum Ingot' } },
        { lock = 'thaumcraft', level = 256, batch = 1, selector = { label = 'Thaumium Ingot' } },

        -- EBF
        { lock = 'EBF', level = 2048, batch = 1, selector = { label = 'Steel Ingot' } },
        { lock = 'EBF', level = 2048, batch = 1, selector = { label = 'Aluminium Ingot' } },
        { lock = 'EBF', level = 2048, batch = 1, selector = { label = 'Stainless Steel Ingot' } },
        { lock = 'EBF', level = 2048, batch = 1, selector = { label = 'Titanium Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Tungsten Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Tungstensteel Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'TPV-Alloy Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Pulsating Iron Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Vibrant Alloy Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Void metal Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Black Steel Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Chrome Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Conductive Iron Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Crystalline Alloy Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Electrical Steel Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Energetic Alloy Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'HSS-G Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Kanthal Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Nichrome Ingot' } },
        { lock = 'EBF', level = 16, batch = 1, selector = { label = 'Rose Gold Ingot' } },
        { lock = 'EBF', level = 16, batch = 1, selector = { label = 'Shadow Metal Ingot' } },
        { lock = 'EBF', level = 16, batch = 1, selector = { label = 'End Steel Ingot' } },
        { lock = 'EBF', level = 16, batch = 1, selector = { label = 'Niobium-Titanium Ingot' } },
        { lock = 'EBF', level = 16, batch = 1, selector = { label = 'Enderium Ingot' } },
        { lock = 'EBF', level = 16, batch = 1, selector = { label = 'Neodymium Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Redstone Alloy Ingot' } },
        { lock = 'EBF', level = 256, batch = 1, selector = { label = 'Silicon Solar Grade (Poly SI) Ingot' } },

        -- Forestry stuff
        { level = 24, batch = 4, selector = { label = 'Diamantine Electron Tube' } },
        { level = 24, batch = 4, selector = { label = 'Iron Electron Tube' } },
        { level = 6, batch = 1, selector = { label = 'Intricate Circuit Board' } },
        { level = 32, batch = 1, selector = { label = 'Apiary' } },
        { lock = 'ForestryAlveary', level = 100, batch = 1, selector = { label = 'Alveary' } },
        { lock = 'ForestryAlveary', level = 10, batch = 1, selector = { label = 'Alveary Fan' } },
        { lock = 'ForestryAlveary', level = 10, batch = 1, selector = { label = 'Alveary Heater' } },
        { lock = 'ForestryAlveary', level = 10, batch = 1, selector = { label = 'Alveary Heater' } },
        { lock = 'ForestryAlveary', level = 10, batch = 1, selector = { label = 'Alveary Hygroregulator' } },
        { lock = 'ForestryAlveary', level = 10, batch = 1, selector = { label = 'Alveary Lighting' } },
        { lock = 'ForestryAlveary', level = 10, batch = 1, selector = { label = 'Electrical Stimulator' } },
        { lock = 'ForestryAlveary', level = 10, batch = 1, selector = { label = 'Mutator' } },

        -- EnderIO Filter stuff
        { lock = 'eio_filter', level = 64, batch = 1, selector = { label = 'Basic Item Filter' } },
        { lock = 'eio_filter', level = 8, batch = 1, selector = { label = 'Advanced Item Filter' } },
        
        -- Pipes, conduits...
        { level = 128, batch = 8, selector = { label = 'Item Conduit' } },
        { level = 128, batch = 8, selector = { label = 'Ender Fluid Conduit' } },
        { lock = 'ae2_cables', level = 128, batch = 8, selector = { label = 'ME Glass Cable - Fluix' } },
        { lock = 'ae2_cables', level = 128, batch = 8, selector = { label = 'ME Dense Covered Cable - Fluix' } },
        { lock = 'ae2_cables', level = 16, batch = 1, selector = { label = 'ME Dense Smart Cable - Fluix' } },
        { lock = 'ae2_cables', level = 64, batch = 1, selector = { label = 'Dense ME Conduit' } },

        { level = 1024, batch = 1, selector = { label = 'Obsidian' } },
        
        -- Blood Magic
        { lock = 'bloodmagic', level = 256, batch = 8, selector = { label = 'Blank Slate' } },
        { lock = 'bloodmagic', level = 256, batch = 8, selector = { label = 'Reinforced Slate' } },
        { lock = 'bloodmagic', level = 256, batch = 8, selector = { label = 'Imbued Slate' } },
        { lock = 'bloodmagic', level = 256, batch = 8, selector = { label = 'Demonic Slate' } },
        { lock = 'bloodmagic', level = 256, batch = 8, selector = { label = 'Ethereal Slate' } },
        { lock = 'bloodmagic', level = 256, batch = 1, selector = { label = 'Ritual Stone' } },
    }
}
